name: Build Docker Image

on:
  push:
    branches:
    tags:
    paths:
      - ".github/workflows/main.yml"
      - "app/**"
      - ".dockerignore"
      - "docker-init.sh"
      - "Dockerfile"
      - "!**.md"
  pull_request:
    paths:
      - ".github/workflows/main.yml"
      - "app/**"
      - ".dockerignore"
      - "docker-init.sh"
      - "Dockerfile"
      - "!**.md"

jobs:
  build-images:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up QEMU for multiarch
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image (multiarch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest
